# Generated by Django 4.2.4 on 2023-09-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ashaworker',
            name='id_proofs',
            field=models.ImageField(blank=True, null=True, upload_to='id_proofs_asha/'),
        ),
        migrations.AddField(
            model_name='ashaworker',
            name='profile_photos',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='ashaworker',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
