# Generated by Django 4.2.4 on 2023-09-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0002_ashaworker_id_proofs_ashaworker_profile_photos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ashaworker',
            old_name='id_proofs',
            new_name='id_proofs_asha',
        ),
    ]
