# Generated by Django 4.2.4 on 2023-09-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0003_rename_id_proofs_ashaworker_id_proofs_asha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ashaworker',
            name='id_proofs_asha',
        ),
    ]
