# Generated by Django 4.2.4 on 2023-09-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0004_remove_ashaworker_id_proofs_asha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ashaworker',
            name='profile_photos',
        ),
    ]
