# Generated by Django 4.2.4 on 2023-09-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0005_remove_ashaworker_profile_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ashaworker',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
