# Generated by Django 4.2.4 on 2023-09-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0006_ashaworker_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ashaworker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ashaworker',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ashaworker',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='ashaworker',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
