# Generated by Django 4.2.4 on 2023-09-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0007_ashaworker_is_active_ashaworker_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashaworker',
            name='password',
            field=models.CharField(default='your_default_password', max_length=128),
        ),
    ]
