# Generated by Django 4.2.4 on 2023-09-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0011_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='ashaworker',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
