# Generated by Django 4.2.4 on 2023-09-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0012_ashaworker_last_login_alter_customuser_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ashaworker',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ashaworker',
            name='is_staff',
        ),
    ]
