# Generated by Django 4.2.4 on 2023-09-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0014_ashaworker_is_asha_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ashaworker',
            name='is_asha_worker',
        ),
        migrations.RemoveField(
            model_name='ashaworker',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='ashaworker',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
