# Generated by Django 4.2.4 on 2023-09-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0018_ashaworker_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ashaworker',
            name='password',
        ),
        migrations.AddField(
            model_name='ashaworker',
            name='admin_set_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
