# Generated by Django 4.2.4 on 2023-09-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0019_remove_ashaworker_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='preferred_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
