# Generated by Django 4.2.4 on 2023-09-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0020_remove_appointment_preferred_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='preferred_datetime',
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_time',
            field=models.CharField(blank=True, choices=[('09:00 AM', '09:00 AM'), ('10:00 AM', '10:00 AM'), ('11:00 AM', '11:00 AM'), ('12:00 PM', '12:00 PM'), ('01:00 PM', '01:00 PM')], max_length=20, null=True),
        ),
    ]
