# Generated by Django 4.2.4 on 2023-09-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0024_alter_ashaworker_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashaworker',
            name='date_of_birth',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ashaworker',
            name='date_of_join',
            field=models.CharField(max_length=100),
        ),
    ]
