# Generated by Django 4.2.4 on 2023-09-14 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0025_alter_ashaworker_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('house_name', models.CharField(blank=True, max_length=100, null=True)),
                ('house_no', models.IntegerField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('ward', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField(blank=True, max_length=6, null=True)),
                ('phone_number', models.IntegerField(blank=True, max_length=12, null=True)),
                ('current_diagnosis', models.CharField(blank=True, max_length=100, null=True)),
                ('past_med_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('surgical_history', models.CharField(blank=True, max_length=100, null=True)),
                ('allergies', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.IntegerField(blank=True, max_length=100, null=True)),
                ('weight', models.IntegerField(blank=True, max_length=100, null=True)),
                ('bmi', models.IntegerField(blank=True, max_length=100, null=True)),
                ('medications', models.CharField(blank=True, max_length=100, null=True)),
                ('dosage', models.CharField(blank=True, max_length=12, null=True)),
                ('frequency', models.CharField(blank=True, max_length=12, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
