# Generated by Django 4.2.4 on 2023-09-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0027_rename_medications_patientprofile_medication_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
