# Generated by Django 4.2.4 on 2023-09-17 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0029_remove_appointment_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='medication_names',
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_names', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=12)),
                ('frequency', models.CharField(max_length=12)),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHapp.patientprofile')),
            ],
        ),
    ]
