# Generated by Django 4.2.4 on 2023-09-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0030_remove_patientprofile_dosage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='dosage',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='frequency',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medication_names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
    ]
