# Generated by Django 4.2.4 on 2023-09-17 12:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0032_remove_appointment_preferred_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='house_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='house_no',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='medical_conditions',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='urgency',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='ward',
        ),
        migrations.AddField(
            model_name='appointment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHapp.patientprofile'),
            preserve_default=False,
        ),
    ]
