# Generated by Django 4.2.4 on 2023-09-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0033_remove_appointment_address_remove_appointment_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='profile',
            new_name='patient_profile',
        ),
    ]
