# Generated by Django 4.2.4 on 2023-09-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0034_rename_profile_appointment_patient_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
