# Generated by Django 4.2.4 on 2023-09-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0037_alter_ashaworker_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ashaworker',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ashaworker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='ashaworker',
            unique_together={('id', 'ward')},
        ),
    ]
