# Generated by Django 4.2.4 on 2023-09-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0038_alter_ashaworker_unique_together_alter_ashaworker_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashaworker',
            name='ward',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
