# Generated by Django 4.2.4 on 2023-09-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0040_appointment_patient_alter_patientprofile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='bmi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
