# Generated by Django 4.2.4 on 2023-09-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0044_appointment_user_alter_appointment_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='id_proof',
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
