# Generated by Django 4.2.4 on 2023-09-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0045_rename_patient_name_appointment_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='medications',
            new_name='medication_names',
        ),
    ]
