# Generated by Django 4.2.4 on 2023-09-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0046_rename_medications_appointment_medication_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
