# Generated by Django 4.2.4 on 2023-09-20 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0048_remove_appointment_appointment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='is_approve',
            new_name='is_approved',
        ),
    ]
