# Generated by Django 4.2.4 on 2023-09-20 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0050_appointment_appointment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_id',
        ),
    ]
