# Generated by Django 4.2.4 on 2023-09-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0051_remove_appointment_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashaworker',
            name='email',
            field=models.EmailField(default=None, max_length=100, unique=True),
        ),
    ]
