# Generated by Django 4.2.4 on 2023-09-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0054_alter_ashaworker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashaworker',
            name='ward',
            field=models.CharField(max_length=100),
        ),
    ]
