# Generated by Django 4.2.4 on 2023-09-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0055_alter_ashaworker_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashaworker',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
    ]
