# Generated by Django 4.2.4 on 2023-09-22 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0057_alter_ashaworker_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ashaworker',
            name='email',
        ),
        migrations.AlterField(
            model_name='ashaworker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ashaworker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
