# Generated by Django 4.2.4 on 2023-09-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0058_remove_ashaworker_email_alter_ashaworker_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ashaworker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
