# Generated by Django 4.2.4 on 2023-09-28 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0065_remove_medicalrecord_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
