# Generated by Django 4.2.4 on 2023-09-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0066_alter_medicalrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
