# Generated by Django 4.2.4 on 2023-09-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0067_alter_medicalrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='current_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='medications_needed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='treatments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
