# Generated by Django 4.2.4 on 2023-09-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0071_day_remove_ashaworkerschedule_available_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ashaworkerschedule',
            old_name='asha_worker',
            new_name='asha_worker_name',
        ),
        migrations.RemoveField(
            model_name='ashaworkerschedule',
            name='available_days',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.AddField(
            model_name='ashaworkerschedule',
            name='available_days',
            field=models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=50, null=True),
        ),
    ]
