# Generated by Django 4.2.4 on 2023-09-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0072_rename_asha_worker_ashaworkerschedule_asha_worker_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ashaworkerschedule',
            old_name='asha_worker_name',
            new_name='Name',
        ),
    ]
