# Generated by Django 4.2.4 on 2023-09-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0073_rename_asha_worker_name_ashaworkerschedule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
