# Generated by Django 4.2.4 on 2023-09-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0075_remove_donation_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ashaworkerschedule',
            name='Name',
        ),
        migrations.AddField(
            model_name='ashaworkerschedule',
            name='ashaworker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='GHapp.ashaworker'),
        ),
        migrations.AlterField(
            model_name='ashaworkerschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ashaworkerschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
