# Generated by Django 4.2.4 on 2023-09-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0076_remove_ashaworkerschedule_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ashaworkerschedule',
            name='ashaworker',
        ),
        migrations.AddField(
            model_name='ashaworkerschedule',
            name='asha_worker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ashaworkerschedule',
            name='available_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ashaworkerschedule',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ashaworkerschedule',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
