# Generated by Django 4.2.4 on 2023-09-29 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0078_alter_ashaworkerschedule_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ashaworkerschedule',
            name='asha_worker',
        ),
        migrations.AddField(
            model_name='ashaworkerschedule',
            name='ashaworker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='GHapp.ashaworker'),
        ),
        migrations.AlterField(
            model_name='ashaworkerschedule',
            name='available_days',
            field=models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=50, null=True),
        ),
    ]
