# Generated by Django 4.2.4 on 2023-09-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0079_remove_ashaworkerschedule_asha_worker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='last_name',
        ),
    ]
