# Generated by Django 4.2.4 on 2023-09-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0080_remove_medicalrecord_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
