# Generated by Django 4.2.4 on 2023-10-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0081_image_is_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Blog Name')),
                ('images', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Blog Images')),
                ('category', models.CharField(choices=[('Health Care', 'Health Care'), ('Child', 'Child'), ('Technology', 'Technology')], max_length=100)),
                ('sub_category', models.CharField(max_length=100, verbose_name='Blog Sub Category')),
                ('description', models.TextField(verbose_name='Blog Description')),
                ('tags', models.CharField(help_text='Separated with a comma', max_length=200, verbose_name='Tags')),
            ],
        ),
    ]
