# Generated by Django 4.2.4 on 2023-10-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0082_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
    ]
