# Generated by Django 4.2.4 on 2023-10-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0083_remove_blog_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='sub_category',
        ),
    ]
