# Generated by Django 4.2.4 on 2023-10-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0084_remove_blog_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
