# Generated by Django 4.2.4 on 2023-10-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0085_blog_author_blog_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='ward',
            field=models.CharField(blank=True, choices=[('ward1', 'Ward 1-VENGATHANAM'), ('ward2', 'Ward 2-PALAPRA'), ('ward3', 'Ward 3-VELICHIYANI'), ('ward4', 'Ward 4-CHOTTY'), ('ward5', 'Ward 5-MANGAPPARA'), ('ward6', 'Ward 6-VADAKKEMALA'), ('ward7', 'Ward 7-PARATHODU'), ('ward8', 'Ward 8-NADUKANI'), ('ward9', 'Ward 9-EDAKKUNNAM'), ('ward10', 'Ward 10-KOORAMTHOOKKU'), ('ward11', 'Ward 11-KOOVAPPALLY'), ('ward12', 'Ward 12-KULAPPURAM'), ('ward13', 'Ward 13-PALAMPRA'), ('ward14', 'Ward 14-MUKKALY'), ('ward15', 'Ward 15-PODIMATTAM'), ('ward16', 'Ward 16-ANAKKALLU'), ('ward17', 'Ward 17-PULKUNNU'), ('ward18', 'Ward 18-PAZHUMALA'), ('ward19', 'Ward 19-CHIRABHAGAM')], max_length=50, null=True),
        ),
    ]
