# Generated by Django 4.2.4 on 2023-10-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0086_alter_patientprofile_ward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AshaworkerSchedule',
        ),
    ]
