# Generated by Django 4.2.4 on 2023-10-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0088_ashaworkerschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='ashaworkerschedule',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ashaworkerschedule',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
