# Generated by Django 4.2.4 on 2023-10-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0089_ashaworkerschedule_name_ashaworkerschedule_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ashaworkerschedule',
            name='ward',
        ),
    ]
