# Generated by Django 4.2.4 on 2023-10-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0090_remove_ashaworkerschedule_ward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AshaworkerSchedule',
        ),
    ]
