# Generated by Django 4.2.4 on 2023-10-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0091_delete_ashaworkerschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AshaworkerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_days', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('ashaworker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='GHapp.ashaworker')),
            ],
        ),
    ]
