# Generated by Django 4.2.4 on 2023-10-03 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0097_remove_appointment_ashaworker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='preferred_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='preferred_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='ashaworker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='GHapp.ashaworker'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GHapp.slots'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
