# Generated by Django 4.2.4 on 2023-10-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0098_rename_preferred_date_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashaworker',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
