# Generated by Django 4.2.4 on 2023-10-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0099_alter_ashaworker_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
