# Generated by Django 4.2.4 on 2023-10-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0101_alter_patientprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
