# Generated by Django 4.2.4 on 2023-10-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0103_hca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hca',
            old_name='Panchayat',
            new_name='panchayat',
        ),
    ]
