# Generated by Django 4.2.4 on 2023-10-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0104_rename_panchayat_hca_panchayat'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
