# Generated by Django 4.2.4 on 2023-10-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0106_ashaworker_reset_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
