# Generated by Django 4.2.4 on 2024-01-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0108_home_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, ' PATIENTS'), (2, 'ASHAWORKER'), (3, 'HCA'), (4, 'ADMIN'), (5, 'NURSE'), (6, 'MEMBER')], default='1', null=True),
        ),
    ]
