# Generated by Django 4.2.4 on 2024-02-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0108_home_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panchayath_Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayath', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
            ],
        ),
    ]
