# Generated by Django 4.2.4 on 2024-03-05 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0109_panchayath_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineName', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('companyName', models.CharField(max_length=100)),
                ('expiryDate', models.DateField(blank=True, null=True)),
                ('contains', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('MedCatId', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('admin_set_password', models.CharField(blank=True, max_length=128, null=True)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('date_of_join', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('taluk', models.CharField(max_length=100)),
                ('Panchayat', models.CharField(max_length=100)),
                ('wardnurse', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='id_proofs/')),
                ('edu_level', models.CharField(blank=True, choices=[('High School', 'High School'), ('Bachelors Degree', 'Bachelors Degree'), ('Masters Degree', 'Masters Degree')], max_length=100, null=True)),
                ('edu_inst', models.CharField(blank=True, max_length=100, null=True)),
                ('year_pass_edu', models.IntegerField(blank=True, null=True)),
                ('edu_certificate', models.FileField(blank=True, null=True, upload_to='edu_cert/')),
                ('add_training', models.CharField(blank=True, max_length=100, null=True)),
                ('add_training_inst', models.CharField(blank=True, max_length=100, null=True)),
                ('year_pass_add', models.IntegerField(blank=True, null=True)),
                ('add_certificate', models.FileField(blank=True, null=True, upload_to='add_cert/')),
                ('reset_password', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='panchayath',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, ' PATIENTS'), (2, 'ASHAWORKER'), (3, 'HCA'), (4, 'ADMIN'), (5, 'NURSE'), (6, 'MEMBER')], default='1', null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='ward',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.BooleanField(default=False)),
                ('noon', models.BooleanField(default=False)),
                ('evening', models.BooleanField(default=False)),
                ('date_of_prescription', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('duration', models.CharField(max_length=100)),
                ('dosages', models.CharField(blank=True, max_length=100, null=True)),
                # ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHapp.appointment')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHapp.medicine')),
                ('nurses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHapp.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='nurse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicine',
            name='MedCatId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHapp.medicinecategory'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='nurses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='GHapp.nurse'),
        ),
        migrations.AlterUniqueTogether(
            name='nurse',
            unique_together={('id', 'wardnurse')},
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('admin_set_password', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('taluk', models.CharField(max_length=100)),
                ('Panchayat', models.CharField(max_length=100)),
                ('wardmem', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='id_proofs/')),
                ('reset_password', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'wardmem')},
            },
        ),
    ]
