# Generated by Django 4.2.4 on 2024-01-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0110_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='ward',
            new_name='wardmem',
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('id', 'wardmem')},
        ),
    ]
