# Generated by Django 4.2.4 on 2024-01-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0111_rename_ward_member_wardmem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='wardmem',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
