# Generated by Django 4.2.4 on 2024-03-05 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0111_alter_member_wardmem_alter_prescription_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='nurses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GHapp.nurse'),
        ),
    ]
