# Generated by Django 4.2.4 on 2024-03-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0112_patientprofile_nurses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='wardmem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
