# Generated by Django 4.2.4 on 2024-03-05 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0114_remove_patientprofile_nurses'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='nurses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='GHapp.nurse'),
        ),
    ]
