# Generated by Django 4.2.4 on 2024-03-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0115_patientprofile_nurses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='wardmem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]

    