# Generated by Django 4.2.4 on 2024-03-06 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0118_prescription_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GHapp.appointment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='morning',
            field=models.BooleanField(default=False),
        ),
    ]
