# Generated by Django 4.2.4 on 2024-03-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0120_auto_20240306_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='evening',
            field=models.BooleanField(default=False),
        ),
    ]
    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(to='GHapp.Appointment', on_delete=models.CASCADE, null=True, blank=True),
        ),
    ]
