# Generated by Django 4.2.4 on 2024-03-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0121_alter_prescription_evening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(default=1,null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='GHapp.appointment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='evening',
            field=models.BooleanField(default=False),
        ),
    ]
