# Generated by Django 4.2.4 on 2024-03-06 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0122_alter_prescription_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GHapp.appointment'),
            preserve_default=False,
        ),
    ]
