# Generated by Django 4.2.4 on 2024-03-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0123_alter_prescription_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
