# Generated by Django 4.2.4 on 2024-03-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0125_prescription_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_model',
            name='evening',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='prescription_model',
            name='morning',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='prescription_model',
            name='noon',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
