# Generated by Django 4.2.4 on 2024-03-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0127_alter_prescription_model_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_model',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
