# Generated by Django 4.2.4 on 2024-03-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0128_alter_prescription_model_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_model',
            name='evening',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription_model',
            name='morning',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription_model',
            name='noon',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
    ]
