# Generated by Django 4.2.4 on 2024-03-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0131_alter_leave_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='ward_asha',
            new_name='ward',
        ),
    ]
