# Generated by Django 4.2.4 on 2024-03-30 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0134_medicinecategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='nurses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GHapp.nurse'),
        ),
    ]
