# Generated by Django 4.2.4 on 2024-03-30 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0135_alter_appointment_nurses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='nurses',
            new_name='nurse',
        ),
    ]
