# Generated by Django 4.2.4 on 2024-04-01 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GHapp', '0136_rename_nurses_appointment_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='GHapp.nurse'),
        ),
    ]
